### PR TITLE
feat: Show blame action on all jobs

### PR DESCRIPTION
**Pull request by LTegtmeier**
This is intended to address #19. 

It adds the action to pipeline jobs . But, the timestamper plugin stores the timestamps differently in a pipeline job. So, it would take larger changes to make it really work.

### CODE REVIEW

**Comment by blorby** [comment]
just a question about this PR - all of our jobs are pipelines, should I wait with this plugin until "pipeline" is fully supported?
in general, it sounds perfect for us :)

**Comment by LTegtmeier** [comment]
Yeah, without completing this change, this plugin won't do anything on pipeline jobs.

I wonder if something that looked at pipeline stages rather than console log matches would work better on pipeline jobs..

**Comment by yanaair** [comment]
should we expect support for pipeline jobs anytime soon?

**Comment by LTegtmeier** [comment]
I have not used Jenkins 2.0 pipelines much and don't use Jenkins a lot anymore since my team uses other CI/CD tools.

This plugin relies on console logs to build the graphs which can be tricky to be accurate with. With Jenkins 2.0 pipeline jobs, I would look into breaking up the stages and using the built-in stage-level timing that is built-in. It even includes average build times for the pipeline and for each stage. From https://www.jenkins.io/2.0/:
image

That said, some time next month, I plan to make a new major release that adds at least basic support for Jenkins 2.0 pipelines and includes updates for #14 and https://github.com/jenkinsci/build-time-blame-plugin/issues/23.

**Comment by LTegtmeier** [comment]
#26 is the last in a series of PRs for the 2.0.0 release which will include these changes. The notes will include full migration steps. Though, they shouldn't be too troublesome.

**Comment by LTegtmeier** [comment]
🚀 This is released in [v2.0.0](https://github.com/jenkinsci/build-time-blame-plugin/releases/tag/v2.0.0). See those notes and the Readme for more details.

**Pull request merged**
